[package]
name = "flarmnet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.28"
thiserror = "1.0.26"

[dev-dependencies]
insta = "1.7.1"
