name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: rustup set profile minimal
      - run: rustup show
      - run: cargo check --all-targets
        env:
            RUSTFLAGS: "-D warnings"

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: rustup set profile minimal
      - run: rustup show
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: rustup set profile minimal
      - run: rustup show
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: rustup set profile minimal
      - run: rustup show
      - run: rustup component add clippy
      - run: cargo clippy -- --deny warnings --allow clippy::unknown-clippy-lints
